version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD:  # root wachtwoord instellen
      MYSQL_DATABASE: employeeservice_db  # De database die automatisch wordt aangemaakt
      MYSQL_USER: user  # Optioneel, maak een aparte gebruiker aan
      MYSQL_PASSWORD: userpassword  # Wachtwoord voor de aangemaakte gebruiker
    ports:
      - "3306:3306"  # Maakt MySQL bereikbaar op poort 3306
    volumes:
      - db_data:/var/lib/mysql  # Persistentie van gegevens

volumes:
  db_data:
