#server.port=8091

#eureka.instance.hostname=localhost
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false
#eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/
#eureka.client.serviceUrl.defaultZone=http://localhost:8061/eureka
#spring.cloud.gateway.discovery.locator.enabled = true
#spring.profiles.active=dev
#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=15672
#spring.rabbitmq.username=java
#spring.rabbitmq.password=java


server.port=8091
eureka.client.serviceUrl.defaultZone=http://localhost:8061/eureka
spring.profiles.active=dev